/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LayoutSidebarRouteRouteImport } from './routes/_layoutSidebar/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SigninSplatRouteImport } from './routes/signin.$'
import { Route as LayoutSidebarProductsRouteImport } from './routes/_layoutSidebar/products'
import { Route as LayoutSidebarProductsIdRouteImport } from './routes/_layoutSidebar/products.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSidebarRouteRoute = LayoutSidebarRouteRouteImport.update({
  id: '/_layoutSidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninSplatRoute = SigninSplatRouteImport.update({
  id: '/signin/$',
  path: '/signin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSidebarProductsRoute = LayoutSidebarProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LayoutSidebarRouteRoute,
} as any)
const LayoutSidebarProductsIdRoute = LayoutSidebarProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutSidebarProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impressum': typeof ImpressumRoute
  '/signup': typeof SignupRoute
  '/products': typeof LayoutSidebarProductsRouteWithChildren
  '/signin/$': typeof SigninSplatRoute
  '/products/$id': typeof LayoutSidebarProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/impressum': typeof ImpressumRoute
  '/signup': typeof SignupRoute
  '/products': typeof LayoutSidebarProductsRouteWithChildren
  '/signin/$': typeof SigninSplatRoute
  '/products/$id': typeof LayoutSidebarProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layoutSidebar': typeof LayoutSidebarRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/impressum': typeof ImpressumRoute
  '/signup': typeof SignupRoute
  '/_layoutSidebar/products': typeof LayoutSidebarProductsRouteWithChildren
  '/signin/$': typeof SigninSplatRoute
  '/_layoutSidebar/products/$id': typeof LayoutSidebarProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/impressum'
    | '/signup'
    | '/products'
    | '/signin/$'
    | '/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/impressum'
    | '/signup'
    | '/products'
    | '/signin/$'
    | '/products/$id'
  id:
    | '__root__'
    | '/'
    | '/_layoutSidebar'
    | '/about'
    | '/impressum'
    | '/signup'
    | '/_layoutSidebar/products'
    | '/signin/$'
    | '/_layoutSidebar/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutSidebarRouteRoute: typeof LayoutSidebarRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ImpressumRoute: typeof ImpressumRoute
  SignupRoute: typeof SignupRoute
  SigninSplatRoute: typeof SigninSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layoutSidebar': {
      id: '/_layoutSidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutSidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/$': {
      id: '/signin/$'
      path: '/signin/$'
      fullPath: '/signin/$'
      preLoaderRoute: typeof SigninSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layoutSidebar/products': {
      id: '/_layoutSidebar/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof LayoutSidebarProductsRouteImport
      parentRoute: typeof LayoutSidebarRouteRoute
    }
    '/_layoutSidebar/products/$id': {
      id: '/_layoutSidebar/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof LayoutSidebarProductsIdRouteImport
      parentRoute: typeof LayoutSidebarProductsRoute
    }
  }
}

interface LayoutSidebarProductsRouteChildren {
  LayoutSidebarProductsIdRoute: typeof LayoutSidebarProductsIdRoute
}

const LayoutSidebarProductsRouteChildren: LayoutSidebarProductsRouteChildren = {
  LayoutSidebarProductsIdRoute: LayoutSidebarProductsIdRoute,
}

const LayoutSidebarProductsRouteWithChildren =
  LayoutSidebarProductsRoute._addFileChildren(
    LayoutSidebarProductsRouteChildren,
  )

interface LayoutSidebarRouteRouteChildren {
  LayoutSidebarProductsRoute: typeof LayoutSidebarProductsRouteWithChildren
}

const LayoutSidebarRouteRouteChildren: LayoutSidebarRouteRouteChildren = {
  LayoutSidebarProductsRoute: LayoutSidebarProductsRouteWithChildren,
}

const LayoutSidebarRouteRouteWithChildren =
  LayoutSidebarRouteRoute._addFileChildren(LayoutSidebarRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutSidebarRouteRoute: LayoutSidebarRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ImpressumRoute: ImpressumRoute,
  SignupRoute: SignupRoute,
  SigninSplatRoute: SigninSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
