/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdmindashboardRouteRouteImport } from './routes/admindashboard/route'
import { Route as LayoutSidebarRouteRouteImport } from './routes/_layoutSidebar/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdmindashboardIndexRouteImport } from './routes/admindashboard/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as DashboardPayoutsRouteImport } from './routes/dashboard/payouts'
import { Route as AdmindashboardSettingsRouteImport } from './routes/admindashboard/settings'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicImpressumRouteImport } from './routes/_public/impressum'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as LayoutSidebarProductsRouteImport } from './routes/_layoutSidebar/products'
import { Route as PublicSigninSplatRouteImport } from './routes/_public/signin.$'
import { Route as LayoutSidebarProductsIdRouteImport } from './routes/_layoutSidebar/products.$id'

const AdmindashboardRouteRoute = AdmindashboardRouteRouteImport.update({
  id: '/admindashboard',
  path: '/admindashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSidebarRouteRoute = LayoutSidebarRouteRouteImport.update({
  id: '/_layoutSidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmindashboardIndexRoute = AdmindashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdmindashboardRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPayoutsRoute = DashboardPayoutsRouteImport.update({
  id: '/dashboard/payouts',
  path: '/dashboard/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmindashboardSettingsRoute = AdmindashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdmindashboardRouteRoute,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/_public/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicImpressumRoute = PublicImpressumRouteImport.update({
  id: '/_public/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/_public/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSidebarProductsRoute = LayoutSidebarProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LayoutSidebarRouteRoute,
} as any)
const PublicSigninSplatRoute = PublicSigninSplatRouteImport.update({
  id: '/_public/signin/$',
  path: '/signin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSidebarProductsIdRoute = LayoutSidebarProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutSidebarProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admindashboard': typeof AdmindashboardRouteRouteWithChildren
  '/products': typeof LayoutSidebarProductsRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/impressum': typeof PublicImpressumRoute
  '/signup': typeof PublicSignupRoute
  '/admindashboard/settings': typeof AdmindashboardSettingsRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/admindashboard/': typeof AdmindashboardIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/products/$id': typeof LayoutSidebarProductsIdRoute
  '/signin/$': typeof PublicSigninSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/products': typeof LayoutSidebarProductsRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/impressum': typeof PublicImpressumRoute
  '/signup': typeof PublicSignupRoute
  '/admindashboard/settings': typeof AdmindashboardSettingsRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/admindashboard': typeof AdmindashboardIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/products/$id': typeof LayoutSidebarProductsIdRoute
  '/signin/$': typeof PublicSigninSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layoutSidebar': typeof LayoutSidebarRouteRouteWithChildren
  '/admindashboard': typeof AdmindashboardRouteRouteWithChildren
  '/_layoutSidebar/products': typeof LayoutSidebarProductsRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/impressum': typeof PublicImpressumRoute
  '/_public/signup': typeof PublicSignupRoute
  '/admindashboard/settings': typeof AdmindashboardSettingsRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/_public/': typeof PublicIndexRoute
  '/admindashboard/': typeof AdmindashboardIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_layoutSidebar/products/$id': typeof LayoutSidebarProductsIdRoute
  '/_public/signin/$': typeof PublicSigninSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admindashboard'
    | '/products'
    | '/about'
    | '/impressum'
    | '/signup'
    | '/admindashboard/settings'
    | '/dashboard/payouts'
    | '/admindashboard/'
    | '/dashboard/'
    | '/products/$id'
    | '/signin/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products'
    | '/about'
    | '/impressum'
    | '/signup'
    | '/admindashboard/settings'
    | '/dashboard/payouts'
    | '/admindashboard'
    | '/dashboard'
    | '/products/$id'
    | '/signin/$'
  id:
    | '__root__'
    | '/_layoutSidebar'
    | '/admindashboard'
    | '/_layoutSidebar/products'
    | '/_public/about'
    | '/_public/impressum'
    | '/_public/signup'
    | '/admindashboard/settings'
    | '/dashboard/payouts'
    | '/_public/'
    | '/admindashboard/'
    | '/dashboard/'
    | '/_layoutSidebar/products/$id'
    | '/_public/signin/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutSidebarRouteRoute: typeof LayoutSidebarRouteRouteWithChildren
  AdmindashboardRouteRoute: typeof AdmindashboardRouteRouteWithChildren
  PublicAboutRoute: typeof PublicAboutRoute
  PublicImpressumRoute: typeof PublicImpressumRoute
  PublicSignupRoute: typeof PublicSignupRoute
  DashboardPayoutsRoute: typeof DashboardPayoutsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  PublicSigninSplatRoute: typeof PublicSigninSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admindashboard': {
      id: '/admindashboard'
      path: '/admindashboard'
      fullPath: '/admindashboard'
      preLoaderRoute: typeof AdmindashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layoutSidebar': {
      id: '/_layoutSidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutSidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admindashboard/': {
      id: '/admindashboard/'
      path: '/'
      fullPath: '/admindashboard/'
      preLoaderRoute: typeof AdmindashboardIndexRouteImport
      parentRoute: typeof AdmindashboardRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/payouts': {
      id: '/dashboard/payouts'
      path: '/dashboard/payouts'
      fullPath: '/dashboard/payouts'
      preLoaderRoute: typeof DashboardPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admindashboard/settings': {
      id: '/admindashboard/settings'
      path: '/settings'
      fullPath: '/admindashboard/settings'
      preLoaderRoute: typeof AdmindashboardSettingsRouteImport
      parentRoute: typeof AdmindashboardRouteRoute
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/impressum': {
      id: '/_public/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof PublicImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layoutSidebar/products': {
      id: '/_layoutSidebar/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof LayoutSidebarProductsRouteImport
      parentRoute: typeof LayoutSidebarRouteRoute
    }
    '/_public/signin/$': {
      id: '/_public/signin/$'
      path: '/signin/$'
      fullPath: '/signin/$'
      preLoaderRoute: typeof PublicSigninSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layoutSidebar/products/$id': {
      id: '/_layoutSidebar/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof LayoutSidebarProductsIdRouteImport
      parentRoute: typeof LayoutSidebarProductsRoute
    }
  }
}

interface LayoutSidebarProductsRouteChildren {
  LayoutSidebarProductsIdRoute: typeof LayoutSidebarProductsIdRoute
}

const LayoutSidebarProductsRouteChildren: LayoutSidebarProductsRouteChildren = {
  LayoutSidebarProductsIdRoute: LayoutSidebarProductsIdRoute,
}

const LayoutSidebarProductsRouteWithChildren =
  LayoutSidebarProductsRoute._addFileChildren(
    LayoutSidebarProductsRouteChildren,
  )

interface LayoutSidebarRouteRouteChildren {
  LayoutSidebarProductsRoute: typeof LayoutSidebarProductsRouteWithChildren
}

const LayoutSidebarRouteRouteChildren: LayoutSidebarRouteRouteChildren = {
  LayoutSidebarProductsRoute: LayoutSidebarProductsRouteWithChildren,
}

const LayoutSidebarRouteRouteWithChildren =
  LayoutSidebarRouteRoute._addFileChildren(LayoutSidebarRouteRouteChildren)

interface AdmindashboardRouteRouteChildren {
  AdmindashboardSettingsRoute: typeof AdmindashboardSettingsRoute
  AdmindashboardIndexRoute: typeof AdmindashboardIndexRoute
}

const AdmindashboardRouteRouteChildren: AdmindashboardRouteRouteChildren = {
  AdmindashboardSettingsRoute: AdmindashboardSettingsRoute,
  AdmindashboardIndexRoute: AdmindashboardIndexRoute,
}

const AdmindashboardRouteRouteWithChildren =
  AdmindashboardRouteRoute._addFileChildren(AdmindashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutSidebarRouteRoute: LayoutSidebarRouteRouteWithChildren,
  AdmindashboardRouteRoute: AdmindashboardRouteRouteWithChildren,
  PublicAboutRoute: PublicAboutRoute,
  PublicImpressumRoute: PublicImpressumRoute,
  PublicSignupRoute: PublicSignupRoute,
  DashboardPayoutsRoute: DashboardPayoutsRoute,
  PublicIndexRoute: PublicIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  PublicSigninSplatRoute: PublicSigninSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
